### ISSUE TITLE
Comment Form Issue

### ISSUE THREAD

**Issue by click2tman** [LamTechConsult/2016slbrapp#1]
Comments are called "Reviews".
1. I want dont want to see the word "Comments". I want it to be replaced by the word "Reviews".
2. I don't want users to see the review/comment form directly in the business detail page. The form should display only after the user click on a buttom with title "Write a Review". 
3. The reviews/comment should have the following fields; Subject, Rating with stars, review, and photos.
4. After a user add a review and click submit, the review added should be displayed on top of the list of reviews because it's the latest. And the form should close.
<img width="375" alt="screen shot 2016-07-14 at 2 54 24 am" src="https://cloud.githubusercontent.com/assets/1200007/16830680/635caf32-496e-11e6-8c36-9f169e9e79b6.png">

**Comment by saurabhd** [comment]
Done
