### ISSUE TITLE
Add business missing fields

### ISSUE THREAD

**Issue by click2tman** [LamTechConsult/2016slbrapp#3]
For add business, focus on the content type Business only at http://slbr.sl/node/add/ltc-business
User should be able to add all the fields in this business; The following fields are very important; Name, Address, Telephone, Geocode: Longitude and Latitude, Email, Website, category, chiefdom, hours,

**Comment by click2tman** [comment]
When I finally get screen that looks like the old one without the new fields you added and submit, I don’t see the business submitted in the backend
<img width="1440" alt="screen shot 2016-07-21 at 1 56 17 am" src="https://cloud.githubusercontent.com/assets/1200007/17012626/f3909230-4ee6-11e6-8549-1d01b3713a94.png">
<img width="1440" alt="screen shot 2016-07-21 at 1 56 22 am" src="https://cloud.githubusercontent.com/assets/1200007/17012622/f38c5c56-4ee6-11e6-8590-0e20fd1d5049.png">
<img width="1440" alt="screen shot 2016-07-21 at 1 56 25 am" src="https://cloud.githubusercontent.com/assets/1200007/17012623/f38c6156-4ee6-11e6-8924-2ffbdc7fd2c7.png">
<img width="1440" alt="screen shot 2016-07-21 at 1 56 28 am" src="https://cloud.githubusercontent.com/assets/1200007/17012625/f3907bce-4ee6-11e6-8d24-f29f8d6fb237.png">
<img width="1440" alt="screen shot 2016-07-21 at 1 56 32 am" src="https://cloud.githubusercontent.com/assets/1200007/17012624/f38dc780-4ee6-11e6-82b6-673d8aa267c1.png">
<img width="1440" alt="screen shot 2016-07-21 at 1 56 36 am" src="https://cloud.githubusercontent.com/assets/1200007/17012627/f391103e-4ee6-11e6-877a-810114ddd065.png">

**Comment by saurabhd** [comment]
Done
