### ISSUE TITLE
Code issues and app not working

### ISSUE THREAD

**Issue by click2tman** [LamTechConsult/2016slbrapp#7]
I have pushed your code to my web server at http://web.app.slbr.sl but visiting it does not produce anything. See the attached pictures. It looks like you have included files in code that are not in the repo.
<img width="1440" alt="screen shot 2016-07-20 at 11 14 47 pm" src="https://cloud.githubusercontent.com/assets/1200007/17010194/c89ef9de-4ecf-11e6-9115-ba79fb06bf35.png">

**Comment by saurabhd** [comment]
Done. Please check now.
